# Generated by Django 5.1.3 on 2024-12-30 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("definitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Cash", "Cash"),
                            ("Current Account", "Current Account"),
                            ("Credit Card", "Credit Card"),
                            ("Saving Account", "Saving Account"),
                            ("Investment", "Investment"),
                            ("Loan", "Loan"),
                            ("Mortgage", "Mortgage"),
                        ],
                        max_length=120,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "initial_amount",
                    models.DecimalField(db_default=0, decimal_places=2, max_digits=15),
                ),
                ("exclude_from_report", models.BooleanField(db_default=False)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="definitions.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="TransferRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=12)),
                ("date", models.DateField()),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="accounts.account",
                    ),
                ),
                (
                    "target_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Record",
                "verbose_name_plural": "Transfer Records",
                "db_table": "accounts_transfer_record",
            },
        ),
    ]
