#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

WORKDIR="/workspaces/app"

python "$WORKDIR/manage.py" migrate
exec python "$WORKDIR/manage.py" runserver_plus 0.0.0.0:8000 --reloader-interval 30
