#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd /workspaces/app

# Standard Django operations
python manage.py migrate --noinput
python manage.py create_superuser

# Start development server
exec python manage.py runserver_plus 0.0.0.0:8000 \
    --reloader-interval 30
