# Generated by Django 5.1.3 on 2025-01-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Currency Code",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Currency Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Exchange Rate"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "source_currency",
                    models.ForeignKey(
                        max_length=3,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_rates",
                        to="definitions.currency",
                        verbose_name="Source Currency",
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        max_length=3,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_rates",
                        to="definitions.currency",
                        verbose_name="Target Currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "db_table": "definitions_exchange_rate",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_currency", "target_currency", "date"),
                        name="definitions_exchange_rate_source_target_unique",
                    )
                ],
            },
        ),
    ]
