# Generated by Django 5.2.4 on 2025-09-19 22:53

from django.db import migrations


def load_currency_data(apps, schema_editor):
    Currency = apps.get_model("definitions", "Currency")

    currencies = [
        {"code": "PHP", "name": "Philippine Peso"},
        {"code": "AED", "name": "UAE Dirham"},
        {"code": "USD", "name": "US Dollar"},
        {"code": "EUR", "name": "Euro"},
        {"code": "GBP", "name": "British Pound"},
        {"code": "JPY", "name": "Japanese Yen"},
        {"code": "CAD", "name": "Canadian Dollar"},
        {"code": "AUD", "name": "Australian Dollar"},
        {"code": "CHF", "name": "Swiss Franc"},
        {"code": "CNY", "name": "Chinese Yuan"},
        {"code": "INR", "name": "Indian Rupee"},
        {"code": "BRL", "name": "Brazilian Real"},
        {"code": "RUB", "name": "Russian Ruble"},
        {"code": "MXN", "name": "Mexican Peso"},
    ]

    for currency_data in currencies:
        Currency.objects.get_or_create(
            code=currency_data["code"], defaults={"name": currency_data["name"]}
        )


def reverse_currency_data(apps, schema_editor):
    Currency = apps.get_model("definitions", "Currency")
    Currency.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("definitions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            load_currency_data,
            reverse_code=reverse_currency_data,
        ),
    ]
