# Generated by Django 5.1.3 on 2024-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("definitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("source_currency", "target_currency", "date"),
                name="definitions_exchange_rate_source_target_unique",
            ),
        ),
    ]
