services:
  django:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: ledger_local_django
    container_name: ledger_local_django
    volumes:
      - ../:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    build:
      context: ..
      dockerfile: docker/postgres/Dockerfile
    image: ledger_local_postgres
    container_name: ledger_local_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - .env

volumes:
  postgres_data:
  postgres_data_backups:
